"""
REVENANT — Falco Kubernetes Runtime Threat Detection Adapter
Ingests and parses runtime behavioral alerts generated by Falco:
- Terminal shell spawned in container (T1059.004)
- Sensitive host volume mounts and privileged container breakout attempts (T1611)
- Unauthorized namespace privilege escalation and namespace evasion
- Namespace network anomalies and unexpected outbound connections.
"""

from __future__ import annotations

import json
import logging
import os
from typing import Any, Dict, List, Optional, Tuple

from adapters.base import AdapterResult, BaseAdapter, to_wsl_path
from control_plane.schemas.models import Finding, HostAsset, Severity
from control_plane.schemas.scope import ScopeManifest

logger = logging.getLogger("revenant.adapters.falco")


class FalcoAdapter(BaseAdapter):
    """Adapter for Falco Kubernetes runtime behavioral security alerts."""

    def __init__(
        self,
        binary_override: Optional[str] = None,
        use_wsl: bool = True,
    ):
        super().__init__(
            name="falco",
            category="cloud",
            version="0.37+",
            binary_override=binary_override,
            use_wsl=use_wsl,
        )

    def is_installed(self) -> bool:
        return True

    def build_command(self, target: str, params: Dict[str, Any]) -> List[str]:
        binary = self.binary_path or "falco"
        rules_file = params.get("rules_file")
        cmd = [binary, "-M", "30"]

        if rules_file:
            cmd.extend(["-r", rules_file])

        if os.path.exists(target):
            cmd.extend(["-e", to_wsl_path(target) if self.use_wsl else target])

        return cmd

    def parse_output(
        self, stdout: str, stderr: str, target: str
    ) -> Tuple[List[Finding], List[HostAsset]]:
        findings: List[Finding] = []
        assets: List[HostAsset] = []

        asset = HostAsset(
            ip="127.0.0.1",
            hostname=f"k8s-runtime:{target or 'cluster-runtime'}",
            metadata={"type": "kubernetes-runtime", "target": target},
        )
        assets.append(asset)

        if not stdout.strip():
            return findings, assets

        # Process each JSON line (Falco streams JSON lines by default)
        for line in stdout.strip().splitlines():
            line = line.strip()
            if not line or not (line.startswith("{") and line.endswith("}")):
                continue

            try:
                alert = json.loads(line)
            except json.JSONDecodeError:
                continue

            rule_name = alert.get("rule", "Falco Runtime Alert")
            priority = alert.get("priority", "").capitalize()
            output_msg = alert.get("output", "")
            fields = alert.get("output_fields", {})
            container_name = fields.get("container.name", fields.get("container.id", "unknown-container"))
            proc_name = fields.get("proc.name", "")
            user_name = fields.get("user.name", "")

            # Severity mapping
            if priority in ["Emergency", "Alert", "Critical"]:
                sev = Severity.CRITICAL
                cvss = 9.2
            elif priority in ["Error", "Warning"]:
                sev = Severity.HIGH
                cvss = 7.8
            elif priority == "Notice":
                sev = Severity.MEDIUM
                cvss = 5.5
            else:
                sev = Severity.LOW
                cvss = 3.0

            # MITRE ATT&CK mapping
            rule_lower = rule_name.lower()
            if "shell" in rule_lower:
                mitre_id = "T1059.004"
                cwe = "CWE-250"
            elif any(k in rule_lower for k in ["breakout", "escape", "privileged", "sensitive mount"]):
                mitre_id = "T1611"
                cwe = "CWE-250"
            elif any(k in rule_lower for k in ["modify", "write below"]):
                mitre_id = "T1565"
                cwe = "CWE-732"
            else:
                mitre_id = "T1613"
                cwe = "CWE-693"

            finding = Finding(
                title=f"Falco Runtime Alert [{priority}]: {rule_name} in {container_name}",
                description=(
                    f"Rule: {rule_name}\n"
                    f"Priority: {priority}\n"
                    f"Container: {container_name}\n"
                    f"Process: {proc_name} (User: {user_name})\n"
                    f"Details: {output_msg}"
                ),
                severity=sev,
                target=target or f"container:{container_name}",
                tool=self.name,
                cvss_score=cvss,
                cwe=cwe,
                mitre_attack_ids=[mitre_id],
                remediation=(
                    f"Investigate runtime event '{rule_name}' in container '{container_name}'. "
                    "Harden PodSecurity admission, restrict container privileges, and enforce seccomp/AppArmor."
                ),
                evidence=json.dumps(alert, indent=2),
            )
            findings.append(finding)

        return findings, assets
